AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create Terraform backend resources (S3 bucket and DynamoDB table)'

Parameters:
  ProjectName:
    Type: String
    Description: Name of your project
    Default: terraform-backend
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-zA-Z0-9-_]*$

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub qwik-tools-${ProjectName}-terraform-state
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: MultiVersionRule
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  TerraformStateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSecureTransport
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !Sub ${TerraformStateBucket.Arn}
              - !Sub ${TerraformStateBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  TerraformLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-terraform-locks
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true